name: Termux Package Build

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Clone Repo
      run: |
        sudo apt install git
        cd $GITHUB_WORKSPACE
        git clone https://github.com/termux/termux-packages
        git clone https://github.com/tapetalarray/android-lxc-lts lxc
        echo "LXC_VER=$(cat ./lxc/termux-package/lxc-lts/build.sh | grep VERSION= | sed -e s/".*="/""/g)" >> $GITHUB_ENV

    - name: Setup Termux-Packages
      run: |
        cd $GITHUB_WORKSPACE/termux-packages
        ./script/setup-ubuntu.sh
        ./script/setup-android-sdk.sh

    - name: Add Package
      run: |
        cd $GITHUB_WORKSPACE
        cp -r ./lxc/termux-package/lxc-lts ./termux-package/packages      

    - name: Build Package
      run: |
        cd $GITHUB_WORKSPACE/termux-packages
        ./build-package.sh -i -a all lxc-lts
        ./build-package.sh -i -a all --format pacman lxc-lts

    - name: Upload Packages
      uses: actions/upload-artifact@v4
      with:
        name: lxc-lts_${{ env.LXC_VER }}_all-arch
        path: ./termux-packages/output/*
